"""atualizando cep para prefixo_cep

Revision ID: 16e20a6bbaa0
Revises: 6745760b4684
Create Date: 2026-04-10 14:47:54.004706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16e20a6bbaa0'
down_revision: Union[str, None] = '6745760b4684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
