"""atualizando nome para nome_vendedor

Revision ID: 6745760b4684
Revises: edfba150c27a
Create Date: 2026-04-10 14:46:57.514897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6745760b4684'
down_revision: Union[str, None] = 'edfba150c27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
