"""atualizando nome para nome_vendedor

Revision ID: edfba150c27a
Revises: 9638e6e0ce23
Create Date: 2026-04-10 14:46:05.036779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edfba150c27a'
down_revision: Union[str, None] = '9638e6e0ce23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
